import { Inter, Nunito } from "next/font/google";
import "./globals.css";
import getCurrentUser from "./libs/auth/route";
import Navbar from "../components/navbar";
import ToastProvider from "../components/providers/ToastProvider";
import Footer from "../components/footer";
import MenuItem from "../components/navbar/MenuItem";

const inter = Nunito({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const currentUser = await getCurrentUser();
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-medium`}>
        {currentUser && <Navbar />}
        <MenuItem currentUser={currentUser} />
        <ToastProvider />
        {children}
        <Footer />
      </body>
    </html>
  );
}
